# PDX-License-Identifier: (GPL-2.0 OR BSD-2-Clause)
#
# Modified archive of the p4lang-project (github.com/p4lang/tutorials/) repository 
# for purely academic purposes. 
#
# 	Author: David Carrascal <davidcawork@gmail.com>
# 	Date:   20 March  2020



BMV2_SWITCH_EXE = simple_switch_grpc
TOPO = scenario/topology.json

include ../utils/Makefile
