# SPDX-License-Identifier: (GPL-2.0 OR BSD-2-Clause)
#
# Modified archive of the xdp-project (github.com/xdp-project) repository 
# for purely academic purposes. 
#
# 	Author: David Carrascal <davidcawork@gmail.com>
# 	Date:   29 Jan 2011

USER_TARGETS := xdp_stats xdp_loader

LIBBPF_DIR = ../libbpf/src/
COMMON_DIR = ../common/
COMMON_OBJS += $(COMMON_DIR)/common_libbpf.o

include $(COMMON_DIR)/common.mk
